url: 'https://www.imaginesoftware.it'
domain: imaginesoftware.it
email: f.bonizzi@imaginesoftware.it
telegram: '@fbonizzi'
github: https://github.com/FrancescoBonizzi
linkedin: https://www.linkedin.com/in/fbonizzi/
plugins:
    - jekyll-sitemap
    - jekyll-compress-images
sass:
    sass_dir: ./_scss
exclude:
    - dev/
    - _compress_images_cache.yml
    - .prettierignore
imageoptim:
    svgo: false
collections:
    homePageHeaderBoxes:
        output: false
    homePageSections:
        output: false
    open-source-projects:
        output: true
    projects-apps:
        output: true
