url: 'https://imaginesoftware.it'
encoding: utf-8
domain: imaginesoftware.it

email: f.bonizzi@imaginesoftware.it
telegram: fbonizzi
github: https://github.com/FrancescoBonizzi
linkedin: https://www.linkedin.com/in/fbonizzi/

piva: 02982280345

plugins:
    - jekyll-sitemap
    - jekyll-compress-images
sass:
    sass_dir: ./_scss

exclude:
    - dev/
    - _compress_images_cache.yml
    - .prettierignore
    - README.md

imageoptim:
    svgo: false

collections:
    homePageHeaderBoxes:
        output: false
    homePageSections:
        output: false
    servicesSections:
        output: false
    open-source-projects:
        output: true
    projects-apps:
        output: true

webrick:
    headers:
        Access-Control-Allow-Origin: "*"